### ISSUE TITLE
Add project license

### ISSUE THREAD

**Issue by ivanalejandro0** [DamonBaker/fuzzy-jira#1]
Hello there, interesting project :), could you please add a LICENSE to it?
That way people know what we can do with it.

For more information you can read Github's documentation about it: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
Or use their license chooser: https://choosealicense.com/

**Comment by DamonBaker** [comment]
Thank you for the advice. I've added a license, feel free to use the software as you like :)
